//============= HOUSES =================================
const houses = {
  first: {
    signs: ["leo"],
    element: "fire",
    exaltation: "aries",
    debilitation: "libra",
    gender: "male",
  },
};
//============= SIGNS =================================
const signs = {
  aries: {
    element: "fire",
    house: 1,
    lord: "mars",
    gender: "male",
    exaltation: "sun",
    debilitation: "saturn",
    direction: "east",
    bodyPart: "head",
    esotericMeanings: ["soul", "consciousness"],
    nakshatras: [
      {
        name: "ashwini",
        degree: "0-13.2 degree aries",
      },
      {
        name: "krittika",
        degree: "26-10 degree aries tauraus",
      },
      {
        name: "Ardra",
        degree: "26-10 degree aries tauraus",
      },
    ],
  },

  taurus: {
    element: "fire",
    house: 1,
    lord: "mars",
    gender: "male",
    exaltation: "sun",
    debilitation: "saturn",
    direction: "east",
    bodyPart: "head",
    esotericMeanings: ["soul", "consciousness"],
    nakshatras: [
      {
        name: "ashwini",
        degree: "0-13.2 degree aries",
      },
      {
        name: "krittika",
        degree: "26-10 degree aries tauraus",
      },
      {
        name: "Ardra",
        degree: "26-10 degree aries tauraus",
      },
    ],
  },
  gemini: {
    element: "fire",
    house: 1,
    lord: "mars",
    gender: "male",
    exaltation: "sun",
    debilitation: "saturn",
    direction: "east",
    bodyPart: "head",
    esotericMeanings: ["soul", "consciousness"],
    nakshatras: [
      {
        name: "ashwini",
        degree: "0-13.2 degree aries",
      },
      {
        name: "krittika",
        degree: "26-10 degree aries tauraus",
      },
      {
        name: "Ardra",
        degree: "26-10 degree aries tauraus",
      },
    ],
  },
  cancer: {
    element: "fire",
    house: 1,
    lord: "mars",
    gender: "male",
    exaltation: "sun",
    debilitation: "saturn",
    direction: "east",
    bodyPart: "head",
    esotericMeanings: ["soul", "consciousness"],
    nakshatras: [
      {
        name: "ashwini",
        degree: "0-13.2 degree aries",
      },
      {
        name: "krittika",
        degree: "26-10 degree aries tauraus",
      },
      {
        name: "Ardra",
        degree: "26-10 degree aries tauraus",
      },
    ],
  },
  leo: {
    element: "fire",
    house: 1,
    lord: "mars",
    gender: "male",
    exaltation: "sun",
    debilitation: "saturn",
    direction: "east",
    bodyPart: "head",
    esotericMeanings: ["soul", "consciousness"],
    nakshatras: [
      {
        name: "ashwini",
        degree: "0-13.2 degree aries",
      },
      {
        name: "krittika",
        degree: "26-10 degree aries tauraus",
      },
      {
        name: "Ardra",
        degree: "26-10 degree aries tauraus",
      },
    ],
  },
  virgo: {
    element: "fire",
    house: 1,
    lord: "mars",
    gender: "male",
    exaltation: "sun",
    debilitation: "saturn",
    direction: "east",
    bodyPart: "head",
    esotericMeanings: ["soul", "consciousness"],
    nakshatras: [
      {
        name: "ashwini",
        degree: "0-13.2 degree aries",
      },
      {
        name: "krittika",
        degree: "26-10 degree aries tauraus",
      },
      {
        name: "Ardra",
        degree: "26-10 degree aries tauraus",
      },
    ],
  },
  libra: {
    element: "fire",
    house: 1,
    lord: "mars",
    gender: "male",
    exaltation: "sun",
    debilitation: "saturn",
    direction: "east",
    bodyPart: "head",
    esotericMeanings: ["soul", "consciousness"],
    nakshatras: [
      {
        name: "ashwini",
        degree: "0-13.2 degree aries",
      },
      {
        name: "krittika",
        degree: "26-10 degree aries tauraus",
      },
      {
        name: "Ardra",
        degree: "26-10 degree aries tauraus",
      },
    ],
  },
  scorpio: {
    element: "fire",
    house: 1,
    lord: "mars",
    gender: "male",
    exaltation: "sun",
    debilitation: "saturn",
    direction: "east",
    bodyPart: "head",
    esotericMeanings: ["soul", "consciousness"],
    nakshatras: [
      {
        name: "ashwini",
        degree: "0-13.2 degree aries",
      },
      {
        name: "krittika",
        degree: "26-10 degree aries tauraus",
      },
      {
        name: "Ardra",
        degree: "26-10 degree aries tauraus",
      },
    ],
  },
  saggitarius: {
    element: "fire",
    house: 1,
    lord: "mars",
    gender: "male",
    exaltation: "sun",
    debilitation: "saturn",
    direction: "east",
    bodyPart: "head",
    esotericMeanings: ["soul", "consciousness"],
    nakshatras: [
      {
        name: "ashwini",
        degree: "0-13.2 degree aries",
      },
      {
        name: "krittika",
        degree: "26-10 degree aries tauraus",
      },
      {
        name: "Ardra",
        degree: "26-10 degree aries tauraus",
      },
    ],
  },
  capricorn: {
    element: "fire",
    house: 1,
    lord: "mars",
    gender: "male",
    exaltation: "sun",
    debilitation: "saturn",
    direction: "east",
    bodyPart: "head",
    esotericMeanings: ["soul", "consciousness"],
    nakshatras: [
      {
        name: "ashwini",
        degree: "0-13.2 degree aries",
      },
      {
        name: "krittika",
        degree: "26-10 degree aries tauraus",
      },
      {
        name: "Ardra",
        degree: "26-10 degree aries tauraus",
      },
    ],
  },
  aquarius: {
    element: "fire",
    house: 1,
    lord: "mars",
    gender: "male",
    exaltation: "sun",
    debilitation: "saturn",
    direction: "east",
    bodyPart: "head",
    esotericMeanings: ["soul", "consciousness"],
    nakshatras: [
      {
        name: "ashwini",
        degree: "0-13.2 degree aries",
      },
      {
        name: "krittika",
        degree: "26-10 degree aries tauraus",
      },
      {
        name: "Ardra",
        degree: "26-10 degree aries tauraus",
      },
    ],
  },
  pisces: {
    element: "fire",
    house: 1,
    lord: "mars",
    gender: "male",
    exaltation: "sun",
    debilitation: "saturn",
    direction: "east",
    bodyPart: "head",
    esotericMeanings: ["soul", "consciousness"],
    nakshatras: [
      {
        name: "ashwini",
        degree: "0-13.2 degree aries",
      },
      {
        name: "krittika",
        degree: "26-10 degree aries tauraus",
      },
      {
        name: "Ardra",
        degree: "26-10 degree aries tauraus",
      },
    ],
  },
};
//============= PLANETS =================================
const planet = {
  sun: {
    signs: ["leo"],
    element: "fire",
    exaltation: "aries",
    debilitation: "libra",
    gender: "male",
    incarnation: "raam",
    cabinet: "king",
    varna: "kshatriya",
    malefic: true,
    guna: "satvik",
    people: ["king", "father", "authority"],
    keyword: ["ego", "soul", "joy", "pride"],
  },
  moon: {
    signs: ["cancer"],
    element: "water",
    exaltation: "taurus",
    debilitation: "scorpio",
    gender: "female",
    incarnation: "krishna",
    cabinet: "queen",
    varna: "vaishya",
    malefic: false,
    guna: "satvik",
    people: ["queen", "mother", "public"],
    keyword: ["emotion", "change"],
  },
  mercury: {
    signs: ["gemini", "virgo"],
    element: "earth",
    exaltation: "virgo",
    debilitation: "pisces",
    gender: "neuter",
    incarnation: "none",
    cabinet: "prince",
    varna: "vaishya",
    malefic: false,
    guna: "rajaasik",
    people: ["sisters", "bua", "siblings"],
    keyword: ["blame"],
  },

  venus: {
    signs: ["taurus", "libra"],
    element: "water",
    exaltation: "pisces",
    debilitation: "virgo",
    gender: "female",
    incarnation: "parashurama",
    cabinet: "ministers",
    varna: "brahmana",
    malefic: false,
    guna: "rajaasik",
    people: ["wife", "female"],
    keyword: ["shukra", "diplomacy", "balance"],
  },
  mars: {
    signs: ["aries", "scorpio"],
    element: "fire",
    exaltation: "capricorn",
    debilitation: "cancer",
    gender: "male",
    incarnation: "narasimha",
    cabinet: "ministers",
    varna: "kshatriya",
    malefic: true,
    guna: "tamasik",
    people: ["soldier", "police", "warrior", "brothers", "friends", "native"],
    keyword: ["vitality", "blood", "anger"],
  },
  jupiter: {
    signs: ["sagittarius", "pisces"],
    element: "aether",
    exaltation: "cancer",
    debilitation: "capricorn",
    gender: "male",
    incarnation: "vamana",
    cabinet: "ministers",
    varna: "brahmana",
    malefic: false,
    guna: "satvik",
    people: ["priest", "father", "teacher"],
    keyword: ["religion", "spirutal-warfare", "yellow-food"],
  },
  saturn: {
    signs: ["capricorn", "aquarius"],
    element: "air",
    exaltation: "libra",
    debilitation: "aries",
    gender: "neuter",
    incarnation: "kurma",
    cabinet: "servant",
    varna: "sudra",
    malefic: true,
    guna: "tamasik",
    people: ["servant", "labourer"],
    keyword: ["hardwork", "struggle", "cold", "old"],
  },
  rahu: {
    signs: ["virgo"],
    element: "fire",
    exaltation: "aries",
    debilitation: "libra",
    gender: "male",
    incarnation: "varaha",
    cabinet: "king",
    varna: "kshatriya",
    malefic: true,
    guna: "satvik",
    people: ["thief", "beggar"],
    keyword: ["illusion", "cheating"],
  },
  ketu: {
    signs: ["pisces"],
    element: "fire",
    exaltation: "scorpio-sagittarius",
    debilitation: "taurus-gemini",
    gender: "male",
    incarnation: "matsya",
    cabinet: "king",
    varna: "kshatriya",
    malefic: true,
    guna: "satvik",
    people: ["ascetic"],
    keyword: ["flag", "achieved"],
  },
};
//============= CONCEPTS =================================
const sudarshanChakra = {
  lagna: {
    nature: "One's concept", // EARTH
  },
  moon: {
    nature: "How the event unfolds", // LORD OF THE NAKSHATRAS
  },
  sun: {
    nature: "Condition of the fullfilment of the concept/event", // RASHI-EFFECTS
  },
};
